# Generated by Django 4.2.2 on 2023-07-13 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_product_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='colour',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='cart',
            name='size',
            field=models.CharField(default='', max_length=50),
        ),
    ]
